linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - revive
    - gosec
    - gocritic
    - misspell
    - bodyclose
    - gofmt
    - goimports
    - whitespace

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-rules:
    - path: handlers/
      linters:
        - gosec
      text: "G204:"
