version: '3'

vars:
  BINARY_NAME: zee-mirror
  EXE: '{{if eq OS "windows"}}.exe{{end}}'
  ENTRY_POINT: ./cmd/zee-mirror

tasks:
  default:
    cmds:
      - task --list

  build:
    cmds:
      - go build -o {{.BINARY_NAME}}{{.EXE}} {{.ENTRY_POINT}}
    sources:
      - ./**/*.go
    generates:
      - "{{.BINARY_NAME}}{{.EXE}}"

  run:
    cmds:
      - go run {{.ENTRY_POINT}}

  clean:
    cmds:
      - rm -f {{.BINARY_NAME}}{{.EXE}}
      - rm -f {{.BINARY_NAME}}
    ignore_error: true

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run ./...

  fmt:
    cmds:
      - go fmt ./...
      - go install golang.org/x/tools/cmd/goimports@latest
      - goimports -w .

  vet:
    cmds:
      - go vet ./...

  security:
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  tidy:
    cmds:
      - go mod tidy

  check:
    cmds:
      - task: tidy
      - task: fmt
      - task: vet
      - task: security
      - task: lint
      - task: test

  all:
    cmds:
      - task: check
      - task: build

  pre-push:
    cmds:
      - task: check

  up:
    cmds:
      - docker compose up -d --build

  down:
    cmds:
      - docker compose down

  logs:
    cmds:
      - docker compose logs -f --no-log-prefix zee-mirror