version: '3'

vars:
  BIN_DIR: bin
  BINARY_NAME: zee-mirror
  EXE: '{{if eq OS "windows"}}.exe{{end}}'
  ENTRY_POINT: ./cmd/zee-mirror

tasks:
  default:
    cmds:
      - task --list

  build:
    cmds:
       # Create bin directory if not exists
      - '{{if eq OS "windows"}}powershell -Command "if (!(Test-Path {{.BIN_DIR}})) { New-Item -ItemType Directory -Path {{.BIN_DIR}} }"{{else}}mkdir -p {{.BIN_DIR}}{{end}}'
      - go build -o {{.BIN_DIR}}/{{.BINARY_NAME}}{{.EXE}} {{.ENTRY_POINT}}
    sources:
      - ./**/*.go
    generates:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}{{.EXE}}"

  run:
    cmds:
      - go run {{.ENTRY_POINT}}

  clean:
    cmds:
      - '{{if eq OS "windows"}}powershell -Command "if (Test-Path {{.BIN_DIR}}) { Remove-Item -Recurse -Force {{.BIN_DIR}} }"{{else}}rm -rf {{.BIN_DIR}}{{end}}'
      - '{{if eq OS "windows"}}powershell -Command "Get-ChildItem -File -Include zee-mirror,zee-mirror-bot,zee-mirror-tmp,zee-mirror.exe,main.exe | Remove-Item -Force"{{else}}rm -f zee-mirror zee-mirror-bot zee-mirror-tmp zee-mirror.exe main.exe{{end}}'
    ignore_error: true

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run ./...

  fmt:
    cmds:
      - go fmt ./...
      - go install golang.org/x/tools/cmd/goimports@latest
      - goimports -w .

  vet:
    cmds:
      - go vet ./...

  security:
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  tidy:
    cmds:
      - go mod tidy

  check:
    cmds:
      - task: tidy
      - task: fmt
      - task: vet
      - task: security
      - task: lint
      - task: test

  all:
    cmds:
      - task: check
      - task: build

  pre-push:
    cmds:
      - task: check

  up:
    cmds:
      - docker compose up -d --build

  down:
    cmds:
      - docker compose down

  logs:
    cmds:
      - docker compose logs -f --no-log-prefix zee-mirror