{{- if .Values.config.rcloneConf }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zee-mirror.fullname" . }}-rclone
  labels:
    {{- include "zee-mirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  rclone.conf: {{ .Values.config.rcloneConf | quote }}
{{- end }}
