apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zee-mirror.fullname" . }}-secret
  labels:
    {{- include "zee-mirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.config.botToken | quote }}
  OWNER_ID: {{ .Values.config.ownerID | quote }}
  WEB_DASHBOARD_TOKEN: {{ .Values.config.dashboardToken | quote }}
  DATABASE_URL: {{ .Values.config.databaseURL | quote }}
  REDIS_URL: {{ .Values.config.redisURL | quote }}
  SENTRY_DSN: {{ .Values.config.sentryDSN | quote }}
