name: Quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Go Tidy Check
        run: task tidy && git diff --exit-code
      - name: Go Vet
        run: task vet
      - name: Run Tests
        run: task test
      - name: Security Check
        run: task security
      - name: Linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...